### ISSUE TITLE
Can this code be used to receive image from TMflow?

### ISSUE THREAD

**Issue by WUPENGDENG** [julespalles/techman-python#1]

**Comment by jvdtoorn** [comment]
Hi Wupeng Deng, this library only provides an interface to send commands to and receive status codes from TMFlow, so it does not support receiving images. For that you should take a look in the TMFlow documentation. I used a simple HTTP server to receive images captured by the Techman robot via a REST API.

**Comment by WUPENGDENG** [comment]
Thank you very much.  Before, I have read the TMflow documentation. But, I did not find how to get receive image from TM robot. Could you please introduce your work about capturing images to me. Thank you very much.

**Comment by jvdtoorn** [comment]
Take a look at the section 3.3.2.8 'External Detection' in the [TMvision manual](https://www.tm-robot.com/en/wpdmdownload/software-manual-tmvision_sw1-82_rev1-00/?ind=1613633783283&filename=Software-Manual-TMvision_SW1.82_Rev1.00_EN.pdf).

**Comment by WUPENGDENG** [comment]
Thank you very much . This section only introduced how to use TM vision detection tool to detect external images, right? If possible, could you please share you project.

**Comment by jvdtoorn** [comment]
Unfortunately I can't because that's disclosed so I can only help you this much.

**Comment by WUPENGDENG** [comment]
Thank you very much. During the process of exporting image, whether do you use external SSD?

**Comment by jvdtoorn** [comment]
Like I said before, I used a custom HTTP server with a REST API. The robot then sent the images it captured to that endpoint, from which I could store the image file.
