### ISSUE TITLE
datatlog robot input 

### ISSUE THREAD

**Issue by NizarMhatli** [julespalles/techman-python#2]
new to this api i used this method conn.add_broadcast_callback an i can get input from the robot but i want to save the input in a different variable and save it csv file i have no idea how to do so any method , function im missing 
thank you for your help

**Comment by jvdtoorn** [comment]
Hello Nizar, have a look at [this tutorial](https://www.tutorialspoint.com/How-to-save-a-Python-Dictionary-to-CSV-file). It explains how to save a dictionary to a CSV file

**Comment by NizarMhatli** [comment]
which function in the techmanpy is used to get the data as dictionary

**Comment by jvdtoorn** [comment]
The `add_broadcast_callback()` function expects a callback function as argument. This callback function receives the robot parameters as a dictionary.

Wrote a quick snippet for you:
```Python
#!/usr/bin/env python

import asyncio
import techmanpy
import csv

def save_dictionary_to_csv(params_dict):
   with open('data.csv', 'w') as file:
      writer = csv.writer(file)
      for parameter, value in params_dict.items():
         writer.writerow([parameter, value])
   print('Wrote parameters to data.csv!')

async def listen():
   async with techmanpy.connect_svr(robot_ip='<robot IP address>') as conn:
      conn.add_broadcast_callback(save_dictionary_to_csv)
      await conn.keep_alive()

asyncio.run(listen())
```
