### ISSUE TITLE
Setting IO of the cobot

### ISSUE THREAD

**Issue by TjorvenVD** [julespalles/techman-python#3]
Hi,

I'm using your library to communicate with my techman cobot, everything is working wonderfull but I now need to set some IO. I saw you added a function to set internal parameters, I'm assuming I can set some IO with this but what would be the (key, value) to for example set DO1 to high? 

The function: await conn.set_value(key, value)

Kind regards

**Comment by TjorvenVD** [comment]
conn.set_value(Ctrl_DO0, 1) for anyone who's wondering, didn't except it to be that easy :)

**Comment by jvdtoorn** [comment]
Thanks for the update, great to hear that you sorted it out!
